project:
  type: website
  preview:
    port: 4200

website:
  page-navigation: true
  title: "Environmental Systems Analysis"
  description: "Homepage for the Fall 2025 version of BEE 4750/5750, Environmental Systems Analysis, at Cornell University."
  site-url: "https://envsys.viveks.me/fall2025"
  repo-url: https://github.com/bee-envsys-cornell/fall2025
  repo-actions: [edit, issue]
  favicon: _assets/logos/favicon.png

  open-graph: true


  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var course.copyright_year >}} Vivek Srikrishnan</span><br>
      See the [About Page](/about.qmd) for credit information.
    center: 
      - text: "<a href='https://creativecommons.org/licenses/by-sa/4.0/deed.en'>LICENSE: CC-BY-SA {{< fa creative-commons-sa >}} <i class='fab fa-creative-commons'></i><i class='fab fa-creative-commons-by'></i><i class='fab fa-creative-commons-sa'></i></a>"
    right: |
      Made with [Julia](https://julialang.org) and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

  navbar:
    pinned: true
    background: "#f7f7f7"
    title: "{{< var course.number >}}"
    search: true
    left:
      - text: "Info"
        menu:
          - syllabus.qmd
          - policies/index.qmd
          - faq/index.qmd
          - setup/index.qmd
      - schedule.qmd
      - text: "Coursework"
        menu:
          - labs/index.qmd
          - hw/index.qmd
          - project/index.qmd
      - text: "Resources"
        menu:
          - tutorials/index.qmd
          - resources/general.qmd
          - resources/julia.qmd
          - resources/ai.qmd
          - resources/github.qmd
          - resources/markdown.qmd
          - resources/dataviz.qmd
    right:
      - href: https://github.com/bee-envsys-cornell/fall2025
        text: "{{< fa brands github >}} GitHub"
        aria-label: "GitHub"
      - href: https://canvas.cornell.edu
        text: "{{< fa regular notebook >}} Canvas"
        aria-label: "Canvas"
      - text: "{{< fa regular comments >}} Ed"
        aria-label: "Ed Discussion"
        url: https://edstem.org
      - text: "{{< fa regular chart-simple >}} Gradescope"
        url: https://gradescope.com
        aria-label: "Gradescope"

  sidebar:
    - title: "Course Policies"
      style: docked
      search: false
      background: "#f7f7f7"
      contents:
        - section: "Policies"
          href: policies/index.qmd
        - section: "Expectations"
          contents:
          - policies/integrity.qmd
          - policies/groups.qmd
        - section: "Grading"
          contents:
          - policies/grading.qmd
          - policies/rubric.qmd
          - policies/homework.qmd
          - policies/exam.qmd
    - title: "Setup and Workflow"
      contents:
        - section: "Tools Setup"
          href: setup/index.qmd
        - section: "Software"
          contents: 
          - setup/julia.qmd
          - setup/git.qmd
          - setup/vscode.qmd
        - section: "Workflow"
          contents:
            - setup: setup/homework.qmd
    - title: "Labs"
      style: docked
      search: false
      background: "#f7f7f7"
      contents:
        - href: labs/index.qmd
          text: "Lab Overview"
        - href: labs/lab01/lab01.qmd
          text: "Lab 1: Data Visualization"  
    - title: "Homework"
      style: docked
      search: false
      background: "#f7f7f7"
      contents:
        - href: hw/index.qmd
          text: "Homework Overview"
        - href: hw/hw01/hw01.qmd
          text: "Homework 1: Intro and EDA"
    - title: "Project"
      style: docked
      search: false
      background: "#f7f7f7"
      contents:
        - href: project/index.qmd
          text: "Project Overview"
        - href: project/proposal.qmd
          text: "Proposal"
        - href: project/presentation.qmd
          text: "Presentation"
        - href: project/peer-review.qmd
          text: "Peer Review"
        - href: project/report.qmd
          text: "Report"
        - href: project/evaluations.qmd
          text: "Team Evaluations"
    - title: "Tutorials"
      style: docked
      search: false
      background: "#f7f7f7"
      contents:
        - tutorials/index.qmd
        - tutorials/julia-basics.qmd
        - tutorials/latex-notebook.qmd
        - tutorials/julia-plots.qmd
format:
  html:
    theme: 
      [simplex, sass/theme.scss]
    mainfont: "Atkinson Hyperlegible"
    copy-code: true
    code-overflow: wrap
    toc: true
    anchor-sections: true
    callout-appearance: simple
    reference-location: margin
    citation-location: margin
    code-annotations: select
    html-math-method: mathjax
    include-in-header: mathjax-config.html
    footnotes-hover: false

bibliography: references.bib
csl: _assets/references/american-geophysical-union.csl

engine: julia
julia:
  exeflags: ["+1.11.5"]
execute: 
  freeze: auto  